# 1. Write a program to print the following using whileloopPuja Na. 
# First 10 Even numbersb. 
# First 10 Odd numbersc. 
# First 10 Natural numbersd. 
# First 10 Whole numbers

#EVEN NUMBERS...............
i=2
while i<=10:
    print(i)
    i=i+2

#ODD NUMBERS................
i=1
while i<=10:
    if i%2!=0:
        print(i)
    i=i+1

#ODD NUMBERS..............
i=1
while i<=10:
    print(i)
    i=i+2

#NATURAL NUMBERS..............
i=1
while i<=10:
    print(i)
    i=i+1

#WHOLE NUMBERS................
i=0
while i<=10:
    print(i)
    i=i+1
